### ISSUE TITLE
Error when running bayesian optimizer for black-box model

### ISSUE THREAD

**Issue by Abdu-Hekal** [EthanJamesLew/AutoKoopman#33]
Error trace:

Tuning BayesianOptTuner:   0%|          | 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/b6062805/Documents/Koopman/AutoKoopman/benchmarks/blackBox.py", line 106, in <module>
    mse, perc_error = test_trajectories(true_trajectories, model, tspan)
  File "/Users/b6062805/Documents/Koopman/AutoKoopman/benchmarks/blackBox.py", line 43, in test_trajectories
    trajectory = model.solve_ivp(
  File "/Users/b6062805/Documents/Koopman/AutoKoopman/autokoopman/core/system.py", line 223, in solve_ivp
    states = np.zeros((len(times), len(self.names)))
TypeError: object of type 'NoneType' has no len()
Tuning BayesianOptTuner:   2%|▎         | 5/200 [00:00<00:36,  5.29it/s]

**Comment by EthanJamesLew** [comment]
See [this comment](https://github.com/EthanJamesLew/AutoKoopman/issues/34#issuecomment-1291341194). We should add an error handler in the benchmark scripts. Also, note that Robot benchmark has a state that is near zero always, causing the relative error to explode (divide by zero).

**Comment by EthanJamesLew** [comment]
Closing
